### ISSUE TITLE
Problem to merge ims files with Terastitcher v1.10.0

### ISSUE THREAD

**Issue by tissota** [abria/TeraStitcher#18]
Hello,

  We have a question for you. We downloaded the version 1.10.0 of Terastitcher and we encountered some issues with it and we think you can help us.
We can import and align our images without problems, but at the merging step,when we try to produce Imaris files, we soon obtain an error. Note that for some times (~ 3 weeks) we where able to do it, but since the 12th of june, we can't stitch anything. 
The software give us an error (see first image).
Knowing the issu #16, we tried to find a file name "resume_status.bin" and delete it, but we have no such a file. We deleted "mdata.bin" instead and we re-obtained our error. We give us too our files generated by terastitcher.

Do you have an idea about what is going on with it?

Thanks in advance,

Audrey Tissot and Stephane Pages.

![merging_error_ims_ts_v1-10-0](https://user-images.githubusercontent.com/29545100/27289865-b6787788-550b-11e7-866a-9b9139c96e68.png)

![ts_files](https://user-images.githubusercontent.com/29545100/27289872-be3186ae-550b-11e7-9319-5749ae93935f.png)

**Comment by abria** [comment]
Could you please try v10.3 at [this link](https://www.dropbox.com/s/bxxw13xo5tbm6f3/TeraStitcher-Qt5-standalone-1.10.3-win64.exe?dl=1)? Previous versions 1.10.x suffered from a major bug that has not been solved. Please let us know if it works.

**Comment by iannellog** [comment]
Alessandro
non ricordo se ri ho detto che anche l'ultimo bug era risolto dalla 1.10.3
Puoi metterla in linea
Giulio

P.S. Ines sta bene? Manca poco Tienimi informato appena ti è possibile

Il 19/Giu/2017 04:35 PM, "Alessandro Bria" <notifications@github.com> ha
scritto:

**Comment by tissota** [comment]
Thank you very much! It works now!
