### ISSUE TITLE
Are there plans to release an OSX build?

### ISSUE THREAD

**Issue by j6k4m8** [abria/TeraStitcher#4]
I'm curious if I should be waiting for a binary release, or if it's time to try my hand building.

**Comment by abria** [comment]
Unfortunately a binary release for Mac OSX requires having different Mac OSX versions for testing or at least an old OSX to produce the binary that works for the more recent versions.

We have OS X 10.11, which means we would hardly be able to produce binaries for OS X <= 10.10.

Which version of Mac OSX do you have? If it is >= 10.11 I can compile it for you. Do you need the command line version or the GUI (Qt-based) version?

**Comment by j6k4m8** [comment]
I have 10.10 — managed to compile it (CLI) last night (and wrote up a [Python wrapper](https://github.com/j6k4m8/pyrastitcher/wiki/Getting-Started) for an upcoming project). I'd be happy to send you my compiled version so others can benefit as well, if you're interested in having it!

**Comment by abria** [comment]
Yes it would be very helpful. Thanks!

BTW, your Python wrapper looks great! Please feel free to contact us by email for further questions / collaboration.

**Comment by j6k4m8** [comment]
Thanks so much! Looking forward to iterating more on that wrapper in the next few weeks, I'll keep you updated! 


> Google Drive: [`terastitcher` for OSX, compiled April 10, 2016 on `master` on 10.10.3 Yosemite (Command-Line only)](https://drive.google.com/open?id=0B-0b9inDTQ0CVUR3c1BfcGxoNk0)

**Comment by abria** [comment]
Thank you! I have added the 10.10 binary to the Download section.

Yes please keep us updated on your project, and feel free to contact for whichever issue you have.

BTW, if you are interested, within TeraStitcher there is an **I/O abstraction layer** called `VirtualVolume`. It allows the client application to fetch image data from many kinds of image volumes despite being unaware of the underlying volume format. This includes also _unstitched volumes_, in which cases stitching is done online and "behind the scenes". A Python wrapper on `VirtualVolume` would be a great piece of software that would allow everybody to use it (since it's currently in C++), but of course that would be a bit more complex than what you have done so far :-).

**Comment by abria** [comment]
Just a quick update: MacOS binaries (both GUI and command line tools) have now been released. Take a look at our [Binary installation packages](https://github.com/abria/TeraStitcher/wiki/Binary-installation-packages) section.

**Comment by iannellog** [comment]
Alex,
sto lavorando alla versione parallela del passo 6 di terastitcher che
intendo sostituire con il teraconverter.
Ho definito un algoritmo per decidere come partizione i dati in modo da
avere tile equilibrate a tutte le risoluzioni e senza perdere voxel ai
bordi delle tile.
Ti allego un pdf che spiega l'algoritmo nel caso te lo voglia leggere.
Allego anche un'implementazione dell'algoritmo in MATLAB. Non e' urgente.
Buon lavoro.

-- Giulio

2016-04-18 16:54 GMT+02:00 Alessandro Bria <notifications@github.com>:

> Just a quick update: MacOS binaries (both GUI and command line tools) have
> now been released. Take a look at our Binary installation packages
> <https://github.com/abria/TeraStitcher/wiki/Binary-installation-packages>
> section.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/abria/TeraStitcher/issues/4#issuecomment-211413807>
>



-- 
____________________________________________________________________

Giulio Iannello
Preside della Facolta' Dipartimentale di Ingegneria
Universita' Campus Bio-Medico di Roma
v. Alvaro del Portillo, 21
00128 Roma, Italy

Tel: +39-06-22541-9602                                              E-mail:
g.iannello@unicampus.it
Fax: +39-06-22541-9609 URL:
https://scholar.google.it/citations?user=L-UJxIgAAAAJ
____________________________________________________________________

**Comment by j6k4m8** [comment]
@abria I think we can consider this closed as per the updated binary downloads section — I'll open up standalone issues later if I run into any questions with pyrastitcher work! A `VirtualVolume` wrapper may be on the horizon... Close at will :)
