### ISSUE TITLE
Bad allocation?

### ISSUE THREAD

**Issue by JimboMahoney** [abria/TeraStitcher#7]
Hi Alessandro,

I was using TeraStitcher successfully yesterday, but today (for a reason that I cannot pin down), I'm getting a "Bad allocation" error, even when using the SAME data that I used yesterday?

![image](https://cloud.githubusercontent.com/assets/7777844/18747177/a7e6313c-80c3-11e6-8063-ef76062bbf83.png)

Although the memory usage thinks I need 33 GB, I watched the peak memory usage yesterday, and it only required ~ 14 GB.

As far as I can see, nothing has changed between yesterday and today - any clues as to what this error means and how to troubleshoot?

Let me know what other information you need.

Many thanks!

**Comment by abria** [comment]
Hi,

the RAM peak calculation is correct, it needs 33 GB of RAM. The "Bad allocation" error means that the operative systems failed to allocate the 33 GB, perhaps they were not available in that particular moment. You should close all other opened applications or try to save your image with 8 bit (which requires half the memory of 16 bit).

**Comment by JimboMahoney** [comment]
Thanks Alessandro, I tried that already (reducing the number of programs running) but even MORE weirdly, it's now working again, despite having more programs running in the background!

I'm watching its peak usage (Peak Working Set in Windows Task Manager) and it's not budging above 14 GB. Does this not mean that's not in fact using 33GB?

**Comment by abria** [comment]
Maybe, TeraStitcher has its own RAM usage optimization based on 3D stitching. That's also why 2D stitching in TeraStitcher generally needs more RAM than 3D stitching (weird, but true). Since your case is 2D stitching, perhaps the RAM peak estimation is not correct.

What kind of images are you stiching? Color or grayscale? How many bits per pixel?

**Comment by JimboMahoney** [comment]
Hi Alessandro,

Yeh, I noticed that more RAM is needed for 2D as well.

The images are 2560 x 2160, 16-bit greyscale = about 11 MB per frame with 64 frames = ~700 MB.

**Comment by JimboMahoney** [comment]
Hi Alessandro,

I think I've found a workaround for the "bad allocation" error:

1) In the Merging step, I select 8-bit, then click Start (error appears)
2) Now I select 16-bit, then click Start again

This time it seems to work OK.

**Comment by abria** [comment]
Actually I re-checked the RAM calculation, and it should not be so high (< 1 GB). There's something  strange here, could you please attach the xml_merging.xml file?

**Comment by JimboMahoney** [comment]
Hi Alessandro,

Sure thing - here you go.

James
[xml_merging.zip](https://github.com/abria/TeraStitcher/files/502410/xml_merging.zip)

**Comment by abria** [comment]
The RAM estimation for 2D stitching is wrong, I have just fixed it. We will release a new version soon (1.9.63) including this and other fixes. 

In your case, the RAM peak should be around 1 GB. So I still cannot explain the bad allocation error. How much RAM do you have? Are you running a 64-bit system?

**Comment by JimboMahoney** [comment]
Hi Alessandro,

16GB RAM and Windows 7 64-bit.

Memory usage peaks at 14 GB for these datasets during merging step and about 256 MB during aligning step.

**Comment by abria** [comment]
Bug fixed. See the latest binary release 1.9.63.

Thanks for the help in figuring out which was the bug.

BTW we are still working to fix the other bug on 2D aligning.

**Comment by JimboMahoney** [comment]
Awesome, thanks!

That's MUCH better! Peak memory hit 2.6 GB with a 2560 x 2160 x 16-bit x 64 fields x 3 Z-stack image = 2 GB total size.

Looking forward to the aligning step being improved!
