### ISSUE TITLE
error while loading shared libraries: libjvm.so

### ISSUE THREAD

**Issue by saskra** [abria/TeraStitcher#77]
I just downloaded this version: https://github.com/abria/TeraStitcher/wiki/Binary-packages#terastitcher-portable-with-support-for-bioformats-command-line-version

But I cannot run Terastitcher at all:

```shell
$ ./terastitcher
./terastitcher: error while loading shared libraries: libjvm.so: cannot open shared object file: No such file or directory
```

I am using Ubuntu 18.04.5 LTS with openjdk version "11.0.9.1" 2020-11-04.

**Comment by iannellog** [comment]
The version that used Java to interface bioformats has not been extensively tested so I cannot exclude that for some machine configurations the executables cannot reach the dynamic library even if it is installed (or that jvm versions conflict)
At the moment I cannot help on this issue

**Comment by saskra** [comment]
Thanks, then I will try a version without Bioformats.
