### ISSUE TITLE
Link to XML file does not work

### ISSUE THREAD

**Issue by saskra** [abria/TeraStitcher#80]
I am using this version: https://github.com/abria/TeraStitcher/wiki/Binary-packages#terastitcher-portable-command-line-version

I want to do this demo: https://github.com/abria/TeraStitcher/wiki/Demo-and-batch-scripts#use-python-mpi-and-gpus

Unfortunately, in step 4 the link to the XML file is down: https://www.dropbox.com/s/hebl7r5l15dbi2j/xml_import.xml?dl=1

**Comment by iannellog** [comment]
I have fixed the broken link, now you should be able to download the xml_import.xml file.

**Comment by saskra** [comment]
Thanks!

**Comment by saskra** [comment]
Same for step 13.

**Comment by iannellog** [comment]
Sorry, I have fixed the broken link, now you should be able to download the xml_merging.xml file.
